/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Legacy tokens kept for backward compatibility
        primary:   '#2563EB',
        'primary-dark': '#1D4ED8',
        navy:      '#1E3A5F',
        accent:    '#7C3AED',
        success:   '#16A34A',
        warning:   '#D97706',
        danger:    '#DC2626',
        surface:   '#F7F9FB',
        border:    '#E2E8F0',
        'text-primary':   '#1E293B',
        'text-secondary': '#475569',

        // Scholarly Edge Design System (Material You)
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-fixed": "#001c3b",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f7f9fb",
        "outline": "#737686",
        "primary-fixed-dim": "#b4c5ff",
        "inverse-primary": "#b4c5ff",
        "background": "#f7f9fb",
        "error-container": "#ffdad6",
        "on-surface-variant": "#434655",
        "surface-dim": "#d8dadc",
        "on-tertiary-container": "#ffede6",
        "on-tertiary": "#ffffff",
        "surface-container": "#eceef0",
        "secondary": "#455f87",
        "on-surface": "#191c1e",
        "outline-variant": "#c3c6d7",
        "inverse-surface": "#2d3133",
        "surface-container-highest": "#e0e3e5",
        "surface-container-high": "#e6e8ea",
        "primary-container": "#2563eb",
        "on-primary": "#ffffff",
        "on-primary-container": "#eeefff",
        "on-error": "#ffffff",
        "tertiary-container": "#bc4800",
        "on-error-container": "#93000a",
        "on-background": "#191c1e",
        "on-secondary-container": "#3e5980",
        "secondary-container": "#b5d0fd",
        "secondary-fixed-dim": "#adc8f5",
        "on-primary-fixed": "#00174b",
        "tertiary-fixed-dim": "#ffb596",
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface-variant": "#e0e3e5",
        "tertiary": "#943700",
        "secondary-fixed": "#d5e3ff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#2d486d",
        "surface-tint": "#0053db",
        "inverse-on-surface": "#eff1f3",
        "error": "#ba1a1a",
        "primary-fixed": "#dbe1ff",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed": "#ffdbcd",
        "on-tertiary-fixed": "#360f00",
      },
      fontFamily: {
        sans:      ['Inter', 'system-ui', 'sans-serif'],
        headline:  ['Manrope', 'sans-serif'],
        body:      ['Inter', 'sans-serif'],
        label:     ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:   '0.5rem',
        xl:   '0.75rem',
        '2xl':'1rem',
        '3xl':'1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
